//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalDay
    {
        public int AdditionalDaysID { get; set; }
        public int EmployeeID { get; set; }
        public System.Guid AdditionaDaysUID { get; set; }
        public int AdditionalDaysNumberOfAdditionalDays { get; set; }
        public string AdditionalDaysReason { get; set; }
        public System.DateTime AdditionalDaysCreatedOn { get; set; }
        public Nullable<System.DateTime> AdditionalDaysDeletedOn { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
