//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public int EmployeeID { get; set; }
        public System.Guid ContractUID { get; set; }
        public int ContractNumber { get; set; }
        public int ContractType { get; set; }
        public string ContractFileName { get; set; }
        public byte[] ContractFile { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public System.DateTime ContractCreatedOn { get; set; }
        public Nullable<System.DateTime> ContractDeletedOn { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
