//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public int EmployeeID { get; set; }
        public System.Guid RequestUID { get; set; }
        public int RequestType { get; set; }
        public string RequestComment { get; set; }
        public int RequestStatus { get; set; }
        public string RequestDenialComment { get; set; }
        public int RequestNumberOfDays { get; set; }
        public string RequestFileName { get; set; }
        public byte[] RequestFile { get; set; }
        public System.DateTime RequestStartDate { get; set; }
        public System.DateTime RequestEndDate { get; set; }
        public System.DateTime RequestCreatedOn { get; set; }
        public Nullable<System.DateTime> RequestDeletedOn { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
